services:
  n8n:
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=warhammer
      - DB_POSTGRESDB_HOST=pg-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=password
    depends_on:
      - pg-n8n
      
  pg-n8n:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=warhammer
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_n8n_data:/var/lib/postgresql/data
volumes:
  pg_n8n_data: